<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Bold.UpgradeCenter</RootNamespace>
    <AssemblyName>Bold.UpgradeCenter</AssemblyName>
    <Product>Bold Upgrade Center</Product>
    <Company>Syncfusion, Inc.</Company>
    <Copyright>Copyright (c) 2001-2026 Syncfusion, Inc.</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Npgsql" Version="8.0.3" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.4.0" />
  </ItemGroup>

</Project>
